from models import db, Question

SEED_QUESTIONS = [
    # === SILLY / CONCRETE ===
    "If you could have any animal as a pet (and it was totally safe), what would you pick?",
    "What's the weirdest food combination you think might actually taste good?",
    "If your stuffed animals could talk, what would they complain about?",
    "Would you rather have spaghetti for hair or marshmallows for fingers?",
    "If you could make one rule that everyone in the world had to follow, what would it be?",
    "What would you name a pet dragon?",
    "If you woke up tomorrow and were invisible, what's the first thing you'd do?",
    "What's the silliest thing you've ever laughed at?",
    "If you had to eat only one food for a whole week, what would it be?",
    "Would you rather be able to fly but only two feet off the ground, or run super fast but only backward?",
    "If your toys came alive at night, what do you think they'd do?",
    "What's the grossest thing you can imagine eating for dinner?",
    "If you could swap places with any animal for a day, which would you choose?",
    "Would you rather have a tail or horns?",
    "If you could invent a new ice cream flavor, what would it be called?",
    "What would happen if it rained lemonade instead of water?",
    "If you could talk to one kind of bug, which would it be?",
    "Would you rather live in a treehouse or a submarine?",
    "What's the funniest sound you can make with your mouth?",
    "If dogs could text, what would they say to you?",
    "Would you rather have wheels instead of feet or springs instead of legs?",
    "If you opened a restaurant, what would you serve?",
    "What would your superhero costume look like?",
    "If you could smell like anything all the time, what would you choose?",
    "What's the best thing about being a kid that grown-ups don't understand?",
    "If you could add a new subject to school, what would it be?",
    "Would you rather burp confetti or sneeze glitter?",
    "If you found a secret door in your house, where would you want it to lead?",
    "What would you do if you woke up on the moon?",
    "If your shadow could do something different from you, what would it do?",
    "What would be the worst superpower to have?",
    "If you could build anything out of LEGO and make it real, what would it be?",
    "Would you rather have a pet dinosaur or a pet unicorn?",

    # === HYPOTHETICAL / IMAGINATIVE ===
    "If you could visit any time period in history, when would you go?",
    "If you found a magic lamp with one wish left, what would you wish for?",
    "If you could design your dream house, what would be the coolest room in it?",
    "If you could have dinner with anyone — alive, dead, or fictional — who would it be?",
    "What would you do if you were the president for a day?",
    "If you could live inside any book or movie, which would you pick?",
    "If you had a time machine, would you go to the past or the future? Why?",
    "If you could give everyone in the world one gift, what would it be?",
    "What would you do if you suddenly had a million dollars?",
    "If you could create a new holiday, what would it celebrate?",
    "If you woke up and could speak every language, what would you do first?",
    "If you could teleport anywhere right now, where would you go?",
    "What kind of robot would you invent to help around the house?",
    "If you could change one thing about how school works, what would it be?",
    "If you could breathe underwater, what would you explore?",
    "What would the world look like if kids were in charge?",
    "If you could bring one fictional character to life to be your friend, who would it be?",
    "If you could make any mythical creature real, which one would you pick?",
    "If there were no gravity for one hour, what would you do?",
    "If you could shrink down to the size of an ant, what would you explore?",
    "What invention does the world need that hasn't been created yet?",
    "If you could design a new planet, what would be special about it?",
    "If every day was your birthday, would that be awesome or terrible?",
    "If you could make one cartoon character your neighbor, who would you pick?",
    "What would school be like if it was run by kids?",
    "If you had your own country, what would the first law be?",
    "If animals could go to school, what subjects would they study?",
    "If you could have any job for a day, what would you try?",
    "What would happen if everyone could read each other's minds?",
    "If you could paint the sky any color, what would you choose?",
    "If trees could walk, where do you think they'd go?",
    "What would you pack in a suitcase for a trip to another dimension?",
    "If you could combine two animals into one, which two would you pick?",
    "If music was a place, what would it look like?",

    # === DEEPER / REFLECTIVE ===
    "What's something you're really proud of that you don't talk about much?",
    "What's the nicest thing someone has done for you recently?",
    "If you could teach everyone in the world one thing, what would it be?",
    "What makes someone a really good friend?",
    "What's something that used to scare you but doesn't anymore?",
    "What do you think is the most important job in the world?",
    "What makes you feel brave?",
    "What's something you wish grown-ups understood better about kids?",
    "If you could fix one problem in the world, which would you choose?",
    "What's a memory that always makes you smile?",
    "What does kindness look like to you?",
    "What's something new you learned this week?",
    "Who is someone you look up to and why?",
    "What's the best advice you've ever been given?",
    "What makes our family special?",
    "If you could write a letter to your future self, what would you say?",
    "What's something you'd like to get better at?",
    "When do you feel the happiest?",
    "What's something about you that people might not know?",
    "How do you like to help other people?",
    "What do you think makes a great day?",
    "Is there something you've been wanting to ask me?",
    "What's a challenge you faced and how did you handle it?",
    "What's something that makes you feel calm or peaceful?",
    "If you could change one thing about yourself, would you? What would it be?",
    "What do you think the world will be like when you grow up?",
    "What's a mistake you learned something important from?",
    "What do you think is more important: being smart or being kind?",
    "When do you feel most like yourself?",
    "What's something you want to do together that we haven't done yet?",
    "What does being brave mean to you?",
    "How do you know when someone really cares about you?",
    "What are three things you're grateful for today?",
    "What's something you'd like to try even if it seems hard?",
]


def seed_questions():
    count = 0
    for text in SEED_QUESTIONS:
        existing = Question.query.filter_by(text=text).first()
        if not existing:
            db.session.add(Question(text=text, source="seed"))
            count += 1
    db.session.commit()
    print(f"Seeded {count} new questions ({len(SEED_QUESTIONS)} total in list)")
